### PR TITLE
Here's some (small) improvements I made to your file. please check them out.

### PR DESCRIPTION
**Pull request by Zikra0**
Changed background colour to black and changed text colour to white. Added third picture to file.

It is up to you if you want to keep these changes but I think it would be humerous if you did.

### CODE REVIEW

**Comment by Zikra0** [comment]
I'm looking forward to seeing what you think of it, Wendel

**Comment by WendelRabanal** [comment]
du er en piece of shit

**Comment by Zikra0** [comment]
Bruh wtf

**Comment by Zikra0** [comment]
Ditt monster

**Pull request closed without merging**
